/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as LeCadreRouteImport } from './routes/le-cadre'
import { Route as PartenariatRouteImport } from './routes/partenariat'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiAssistantRouteImport } from './routes/api.assistant'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as EquipeSlugRouteImport } from './routes/equipe.$slug'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes.$slug'
import { Route as RessourcesAudioRouteImport } from './routes/ressources.audio'
import { Route as RessourcesDocumentsRouteImport } from './routes/ressources.documents'
import { Route as RessourcesGalerieRouteImport } from './routes/ressources.galerie'
import { Route as RessourcesVideoRouteImport } from './routes/ressources.video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const LeCadreRoute = LeCadreRouteImport.update({
  id: '/le-cadre',
  path: '/le-cadre',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenariatRoute = PartenariatRouteImport.update({
  id: '/partenariat',
  path: '/partenariat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeSlugRoute = EquipeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EquipeRoute,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgrammesRoute,
} as any)
const RessourcesAudioRoute = RessourcesAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesDocumentsRoute = RessourcesDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesGalerieRoute = RessourcesGalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesVideoRoute = RessourcesVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => RessourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/gestion': typeof GestionRoute
  '/le-cadre': typeof LeCadreRoute
  '/partenariat': typeof PartenariatRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/ressources': typeof RessourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/contact': typeof ApiContactRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/ressources/audio': typeof RessourcesAudioRoute
  '/ressources/documents': typeof RessourcesDocumentsRoute
  '/ressources/galerie': typeof RessourcesGalerieRoute
  '/ressources/video': typeof RessourcesVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/gestion': typeof GestionRoute
  '/le-cadre': typeof LeCadreRoute
  '/partenariat': typeof PartenariatRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/ressources': typeof RessourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/contact': typeof ApiContactRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/ressources/audio': typeof RessourcesAudioRoute
  '/ressources/documents': typeof RessourcesDocumentsRoute
  '/ressources/galerie': typeof RessourcesGalerieRoute
  '/ressources/video': typeof RessourcesVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/gestion': typeof GestionRoute
  '/le-cadre': typeof LeCadreRoute
  '/partenariat': typeof PartenariatRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/ressources': typeof RessourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/contact': typeof ApiContactRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/ressources/audio': typeof RessourcesAudioRoute
  '/ressources/documents': typeof RessourcesDocumentsRoute
  '/ressources/galerie': typeof RessourcesGalerieRoute
  '/ressources/video': typeof RessourcesVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/equipe'
    | '/gestion'
    | '/le-cadre'
    | '/partenariat'
    | '/programmes'
    | '/ressources'
    | '/sitemap.xml'
    | '/api/assistant'
    | '/api/contact'
    | '/equipe/$slug'
    | '/programmes/$slug'
    | '/ressources/audio'
    | '/ressources/documents'
    | '/ressources/galerie'
    | '/ressources/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/equipe'
    | '/gestion'
    | '/le-cadre'
    | '/partenariat'
    | '/programmes'
    | '/ressources'
    | '/sitemap.xml'
    | '/api/assistant'
    | '/api/contact'
    | '/equipe/$slug'
    | '/programmes/$slug'
    | '/ressources/audio'
    | '/ressources/documents'
    | '/ressources/galerie'
    | '/ressources/video'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/equipe'
    | '/gestion'
    | '/le-cadre'
    | '/partenariat'
    | '/programmes'
    | '/ressources'
    | '/sitemap.xml'
    | '/api/assistant'
    | '/api/contact'
    | '/equipe/$slug'
    | '/programmes/$slug'
    | '/ressources/audio'
    | '/ressources/documents'
    | '/ressources/galerie'
    | '/ressources/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EquipeRoute: typeof EquipeRouteWithChildren
  GestionRoute: typeof GestionRoute
  LeCadreRoute: typeof LeCadreRoute
  PartenariatRoute: typeof PartenariatRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  RessourcesRoute: typeof RessourcesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-cadre': {
      id: '/le-cadre'
      path: '/le-cadre'
      fullPath: '/le-cadre'
      preLoaderRoute: typeof LeCadreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenariat': {
      id: '/partenariat'
      path: '/partenariat'
      fullPath: '/partenariat'
      preLoaderRoute: typeof PartenariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/$slug': {
      id: '/equipe/$slug'
      path: '/$slug'
      fullPath: '/equipe/$slug'
      preLoaderRoute: typeof EquipeSlugRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/ressources/audio': {
      id: '/ressources/audio'
      path: '/audio'
      fullPath: '/ressources/audio'
      preLoaderRoute: typeof RessourcesAudioRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/documents': {
      id: '/ressources/documents'
      path: '/documents'
      fullPath: '/ressources/documents'
      preLoaderRoute: typeof RessourcesDocumentsRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/galerie': {
      id: '/ressources/galerie'
      path: '/galerie'
      fullPath: '/ressources/galerie'
      preLoaderRoute: typeof RessourcesGalerieRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/video': {
      id: '/ressources/video'
      path: '/video'
      fullPath: '/ressources/video'
      preLoaderRoute: typeof RessourcesVideoRouteImport
      parentRoute: typeof RessourcesRoute
    }
  }
}

interface EquipeRouteChildren {
  EquipeSlugRoute: typeof EquipeSlugRoute
}

const EquipeRouteChildren: EquipeRouteChildren = {
  EquipeSlugRoute: EquipeSlugRoute,
}

const EquipeRouteWithChildren =
  EquipeRoute._addFileChildren(EquipeRouteChildren)

interface ProgrammesRouteChildren {
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesSlugRoute: ProgrammesSlugRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

interface RessourcesRouteChildren {
  RessourcesAudioRoute: typeof RessourcesAudioRoute
  RessourcesDocumentsRoute: typeof RessourcesDocumentsRoute
  RessourcesGalerieRoute: typeof RessourcesGalerieRoute
  RessourcesVideoRoute: typeof RessourcesVideoRoute
}

const RessourcesRouteChildren: RessourcesRouteChildren = {
  RessourcesAudioRoute: RessourcesAudioRoute,
  RessourcesDocumentsRoute: RessourcesDocumentsRoute,
  RessourcesGalerieRoute: RessourcesGalerieRoute,
  RessourcesVideoRoute: RessourcesVideoRoute,
}

const RessourcesRouteWithChildren = RessourcesRoute._addFileChildren(
  RessourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EquipeRoute: EquipeRouteWithChildren,
  GestionRoute: GestionRoute,
  LeCadreRoute: LeCadreRoute,
  PartenariatRoute: PartenariatRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  RessourcesRoute: RessourcesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
